# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Résumé
root: 
resume:
  name: Hana Chen
  profile: A dynamic, high-performing third-year digital infrastructure engineering student with high passion and experience in Architecture, engineering and construction (AEC) industry. A detail-oriented and quick learner with strong analytical and problem-solving skills. With an extensive background in Revit, AutoCAD, ArcGIS and Adobe software, as well as excellent collaborating skills in real life projects.
  jobtitle: Graduates
  contact:
    - icon: fa-envelope
      text: youremail@example.com
    - icon: fa-phone-square
      text: your-phone-num
    - icon: fa-globe
      text: weiychen9.github.io
      link: https://weiychen9.github.io/
    - icon: fa-github
      text: weiychen9
      link: https://github.com/weiychen9
  education:
    - university: The university of Melbourne
      duration: 2020 - 2023
      location: VIC
      major: Bachelor of Design  digital infrastructure engineering
    - university: University of New South Wales
      duration: 2018
      major: UNSW Foundation Studies
      location: NSW

  skills:
    - title: Design
      items: Revit, AutoCad, Photoshop, Adobe Illustrator, Adobe InDesign, SketchUp
    - title: Progremming
      items: C, Python
    - title: Management
      items: Engineering risk, Project management, Continous improvement & innovations
  experience:
    - title: Art Tutor
      duration: 2021
      company: Little Monet education, Zhejiang
      description: 
        - Collaborating with the teaching team on designing suitable creative bilingual art classes for student. Participating in class teaching
    - title: Internship
      duration: 2020
      company: The department of urban planning and regional development, Zhejiang
      description: Engaging with the project site visit and site analysis. Cooperating with professionals from different disciplines and evolving the project management process. Using various software such as ArcGIS, PS, and Autocad to develop strategic plans and a sequence of detailed drawings
    - title: Volunteer
      duration: 2019
      company: IndigiGrow, NSW
      description: Indigenous plants propagation and care
  projects:
    - name: 江桥村土地规划和美食街改造项
      contribution: Creator and maintainer.
      description: 场地调研 + 后期分析图绘制 (业态分布 / 交通流线 / 景观流线 / 楼层高度与建筑密度 )
      details: 
        - 记录在社区会议,专家会议收集到的改造需求与意见,
        - 帮助总设计师整理项目整体设计大纲
        - 检查测绘数据是否与场地实况有出入
        - 根据总设计师的指导意见绘制CAD图纸 + 平面彩图(ps)
        - 根据反馈意见以及项目方案的变动修改图纸
        - 进行工程项目风险分析并制定相对应的风险管理计划
        - 用gantt chart进行施工成本核算和项目进度管理
        - 整合项目资料交接给其他部门
    - name: 卫生院迁建工程
      description: 与土地规划部门交涉规划用地范围,通过结合gis数据分析,确定卫生院搬迁拟建设位置
      contribution: Creator and maintainer.
      details: 
        - 进行外围绿化带以及卫生院内部植物种植分析
        - 绘制平面彩图, 各项分析图纸 以及楼层平面图
        - 使用sketchup进行卫生院3d模型制作及效果图渲染
        - 整合资料, 排版成投标文书以及ppt
  languages:
    - name: English
      proficiency: Work proficiency
    - name: Mandarin Chinese
      proficiency: Native
    - name: Korean
      proficiency: Fluent
      
subtitle: ''
description: ''
keywords:
author: John Doe
language: en
timezone: ''

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: http://example.com
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: hexo-crisp-minimal-resume

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repo: git@github.com:weiychen9/weiychen9.github.io.git
  branch: manual-deploy
